export const experts = [
  {
    id: '1',
    photo: 'http://placecorgi.com/160',
    name: 'Наталья Гилярова',
    specialization: 'Онкологица',
  },
  {
    id: '2',
    photo: 'http://placecorgi.com/160',
    name: 'Юрий Павлов',
    specialization: 'Онколог',
  },
  {
    id: '3',
    photo: 'http://placecorgi.com/160',
    name: 'Владимир Свистунов',
    specialization: 'Онколог',
  },
  {
    id: '4',
    photo: 'http://placecorgi.com/160',
    name: 'Андрей Розов',
    specialization: 'Онколог',
  },
  {
    id: '5',
    photo: 'http://placecorgi.com/160',
    name: 'Пётр Будинин',
    specialization: 'Онколог',
  },
  {
    id: '6',
    photo: 'http://placecorgi.com/160',
    name: 'Юрий Павлов',
    specialization: 'Онколог',
  },
  {
    id: '7',
    photo: 'http://placecorgi.com/160',
    name: 'Владимир Свистунов',
    specialization: 'Онколог',
  },
  {
    id: '8',
    photo: 'http://placecorgi.com/160',
    name: '',
    specialization: 'Онколог',
  },
  {
    id: '9',
    photo: 'http://placecorgi.com/160',
    name: 'Андрей Розов',
    specialization: 'Онколог',
  },
  {
    id: '10',
    photo: 'http://placecorgi.com/160',
    name: 'Владимир Свистунов',
    specialization: 'Онколог',
  },
  {
    id: '11',
    photo: 'http://placecorgi.com/160',
    name: 'Владимир Свистунов',
    specialization: 'Онколог',
  },
  {
    id: '12',
    photo: 'http://placecorgi.com/160',
    name: 'Владимир Свистунов',
    specialization: 'Онколог',
  },
  {
    id: '13',
    photo: 'http://placecorgi.com/160',
    name: 'Владимир Свистунов',
    specialization: 'Онколог',
  },
  {
    id: '14',
    photo: 'http://placecorgi.com/160',
    name: 'Владимир Свистунов',
    specialization: 'Онколог',
  },
  {
    id: '15',
    photo: 'http://placecorgi.com/160',
    name: 'Владимир Свистунов',
    specialization: 'Онколог',
  },
]
