import { NON_BREAKING_SPACE } from '@app/lib/config'

export const partners = [
  {
    id: '1',
    type: 'donor',
    img: 'http://placecorgi.com/120/40',
    label: 'DONOR',
    sum: '2 000 000',
    info: `Доноры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '2',
    type: 'donor',
    img: 'http://placecorgi.com/120/40',
    label: 'OLYMPUS',
    sum: '2 000 000',
    info: `Доноры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '3',
    type: 'donor',
    img: 'http://placecorgi.com/120/40',
    label: 'SIEMENS',
    sum: '2 000 000',
    info: `Доноры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '4',
    type: 'donor',
    img: 'http://placecorgi.com/120/40',
    label: 'NESTLE',
    sum: '2 000 000',
    info: `Доноры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '5',
    type: 'donor',
    img: 'http://placecorgi.com/120/40',
    label: 'AVON',
    sum: '2 000 000',
    info: `Доноры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '6',
    type: 'donor',
    img: 'http://placecorgi.com/120/40',
    label: 'GE HEALTHCARE',
    sum: '2 000 000',
    info: `Доноры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '7',
    type: 'donor',
    img: 'http://placecorgi.com/120/40',
    label: 'ЮНИКС',
    sum: '2 000 000',
    info: `Доноры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '8',
    type: 'donor',
    img: 'http://placecorgi.com/120/40',
    label: 'BD',
    sum: '2 000 000',
    info: `Доноры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '9',
    type: 'donor',
    img: 'http://placecorgi.com/120/40',
    label: 'ROCHE',
    sum: '2 000 000',
    info: `Доноры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '10',
    type: 'donor',
    img: 'http://placecorgi.com/120/40',
    label: 'MSD',
    sum: '2 000 000',
    info: `Доноры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '11',
    type: 'donor',
    img: 'http://placecorgi.com/120/40',
    label: 'NESTLE',
    sum: '2 000 000',
    info: `Доноры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '12',
    type: 'donor',
    img: 'http://placecorgi.com/120/40',
    label: 'MSD',
    sum: '2 000 000',
    info: `Доноры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '13',
    type: 'donor',
    img: 'http://placecorgi.com/120/40',
    label: 'BIOCAD',
    sum: '2 000 000',
    info: `Доноры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '14',
    type: 'corp',
    img: 'http://placecorgi.com/120/40',
    label: 'CORP',
    sum: '2 000 000',
    info: `Корпоративные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '15',
    type: 'corp',
    img: 'http://placecorgi.com/120/40',
    label: 'OLYMPUS',
    sum: '2 000 000',
    info: `Корпоративные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '16',
    type: 'corp',
    img: 'http://placecorgi.com/120/40',
    label: 'SIEMENS',
    sum: '2 000 000',
    info: `Корпоративные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '17',
    type: 'corp',
    img: 'http://placecorgi.com/120/40',
    label: 'NESTLE',
    sum: '2 000 000',
    info: `Корпоративные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '18',
    type: 'corp',
    img: 'http://placecorgi.com/120/40',
    label: 'AVON',
    sum: '2 000 000',
    info: `Корпоративные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '19',
    type: 'corp',
    img: 'http://placecorgi.com/120/40',
    label: 'GE HEALTHCARE',
    sum: '2 000 000',
    info: `Корпоративные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '20',
    type: 'corp',
    img: 'http://placecorgi.com/120/40',
    label: 'ЮНИКС',
    sum: '2 000 000',
    info: `Корпоративные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '21',
    type: 'corp',
    img: 'http://placecorgi.com/120/40',
    label: 'BD',
    sum: '2 000 000',
    info: `Корпоративные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '22',
    type: 'corp',
    img: 'http://placecorgi.com/120/40',
    label: 'ROCHE',
    sum: '2 000 000',
    info: `Корпоративные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '23',
    type: 'corp',
    img: 'http://placecorgi.com/120/40',
    label: 'MSD',
    sum: '2 000 000',
    info: `Корпоративные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '24',
    type: 'corp',
    img: 'http://placecorgi.com/120/40',
    label: 'NESTLE',
    sum: '2 000 000',
    info: `Корпоративные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '25',
    type: 'corp',
    img: 'http://placecorgi.com/120/40',
    label: 'MSD',
    sum: '2 000 000',
    info: `Корпоративные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '26',
    type: 'corp',
    img: 'http://placecorgi.com/120/40',
    label: 'BIOCAD',
    sum: '2 000 000',
    info: `Корпоративные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },

  {
    id: '27',
    type: 'infoPartner',
    img: 'http://placecorgi.com/120/40',
    label: 'INFO PARTNER',
    sum: '2 000 000',
    info: `Корпоративные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '28',
    type: 'infoPartner',
    img: 'http://placecorgi.com/120/40',
    label: 'OLYMPUS',
    sum: '2 000 000',
    info: `Информационные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '29',
    type: 'infoPartner',
    img: 'http://placecorgi.com/120/40',
    label: 'SIEMENS',
    sum: '2 000 000',
    info: `Информационные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '30',
    type: 'infoPartner',
    img: 'http://placecorgi.com/120/40',
    label: 'NESTLE',
    sum: '2 000 000',
    info: `Информационные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '31',
    type: 'infoPartner',
    img: 'http://placecorgi.com/120/40',
    label: 'AVON',
    sum: '2 000 000',
    info: `Информационные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '32',
    type: 'infoPartner',
    img: 'http://placecorgi.com/120/40',
    label: 'GE HEALTHCARE',
    sum: '2 000 000',
    info: `Информационные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '33',
    type: 'infoPartner',
    img: 'http://placecorgi.com/120/40',
    label: 'ЮНИКС',
    sum: '2 000 000',
    info: `Информационные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '34',
    type: 'infoPartner',
    img: 'http://placecorgi.com/120/40',
    label: 'BD',
    sum: '2 000 000',
    info: `Информационные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '35',
    type: 'infoPartner',
    img: 'http://placecorgi.com/120/40',
    label: 'ROCHE',
    sum: '2 000 000',
    info: `Информационные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '36',
    type: 'infoPartner',
    img: 'http://placecorgi.com/120/40',
    label: 'MSD',
    sum: '2 000 000',
    info: `Информационные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '37',
    type: 'infoPartner',
    img: 'http://placecorgi.com/120/40',
    label: 'NESTLE',
    sum: '2 000 000',
    info: `Информационные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '38',
    type: 'infoPartner',
    img: 'http://placecorgi.com/120/40',
    label: 'MSD',
    sum: '2 000 000',
    info: `Информационные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '39',
    type: 'infoPartner',
    img: 'http://placecorgi.com/120/40',
    label: 'BIOCAD',
    sum: '2 000 000',
    info: `Информационные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },

  {
    id: '40',
    type: 'infrastructurePartner',
    img: 'http://placecorgi.com/120/40',
    label: 'INFRASRUCTURE PARNTER',
    sum: '2 000 000',
    info: `Инфраструктурные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '41',
    type: 'infrastructurePartner',
    img: 'http://placecorgi.com/120/40',
    label: 'OLYMPUS',
    sum: '2 000 000',
    info: `Инфраструктурные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '42',
    type: 'infrastructurePartner',
    img: 'http://placecorgi.com/120/40',
    label: 'SIEMENS',
    sum: '2 000 000',
    info: `Инфраструктурные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '43',
    type: 'infrastructurePartner',
    img: 'http://placecorgi.com/120/40',
    label: 'NESTLE',
    sum: '2 000 000',
    info: `Инфраструктурные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '44',
    type: 'infrastructurePartner',
    img: 'http://placecorgi.com/120/40',
    label: 'AVON',
    sum: '2 000 000',
  },
  {
    id: '45',
    type: 'infrastructurePartner',
    img: 'http://placecorgi.com/120/40',
    label: 'GE HEALTHCARE',
    sum: '2 000 000',
    info: `Инфраструктурные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '46',
    type: 'infrastructurePartner',
    img: 'http://placecorgi.com/120/40',
    label: 'ЮНИКС',
    sum: '2 000 000',
    info: `Инфраструктурные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '47',
    type: 'infrastructurePartner',
    img: 'http://placecorgi.com/120/40',
    label: 'BD',
    sum: '2 000 000',
    info: `Инфраструктурные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '48',
    type: 'infrastructurePartner',
    img: 'http://placecorgi.com/120/40',
    label: 'ROCHE',
    sum: '2 000 000',
    info: `Инфраструктурные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '49',
    type: 'infrastructurePartner',
    img: 'http://placecorgi.com/120/40',
    label: 'MSD',
    sum: '2 000 000',
    info: `Инфраструктурные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '50',
    type: 'infrastructurePartner',
    img: 'http://placecorgi.com/120/40',
    label: 'NESTLE',
    sum: '2 000 000',
    info: `Инфраструктурные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '51',
    type: 'infrastructurePartner',
    img: 'http://placecorgi.com/120/40',
    label: 'MSD',
    sum: '2 000 000',
    info: `Инфраструктурные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
  {
    id: '52',
    type: 'infrastructurePartner',
    img: 'http://placecorgi.com/120/40',
    label: 'BIOCAD',
    sum: '2 000 000',
    info: `Инфраструктурные партнеры выделяют дополнительные средства на${NON_BREAKING_SPACE}консультации для своих сотрудников. Если вы${NON_BREAKING_SPACE}являетесь сотрудником одной из${NON_BREAKING_SPACE}этих компаний, укажите это в${NON_BREAKING_SPACE}своей заявке.`,
  },
]
