version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8.11.1

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - js-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: js-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Lint Code
          command: yarn s lint

  test:
    docker:
      - image: circleci/node:8.11.1

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - js-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: js-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Unit Test
          command: yarn test

  types:
    docker:
      - image: circleci/node:8.11.1

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - js-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: js-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Check Typings
          command: yarn types

  cicular:
    docker:
      - image: circleci/node:8.11.1

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - js-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: js-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Check Circular Dependency
          command: yarn circular

  push:
    docker:
      - image: docker:17.05.0-ce-git

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup Env
          command: |
            echo 'export IMAGE_TAG=${CIRCLE_TAG:-latest}' >> $BASH_ENV
            echo 'export IMAGE_NAME=oncohelp-web' >> $BASH_ENV
      - run:
          name: Build and push Docker image
          command: |
            source $BASH_ENV
            docker build -t breadheadhub/$IMAGE_NAME:$IMAGE_TAG .
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
            docker push breadheadhub/$IMAGE_NAME:$IMAGE_TAG

  push_stable:
    docker:
      - image: docker:17.05.0-ce-git

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup Env
          command: |
            echo 'export IMAGE_TAG=stable' >> $BASH_ENV
            echo 'export IMAGE_NAME=oncohelp-web' >> $BASH_ENV
      - run:
          name: Build and push Docker image
          command: |
            source $BASH_ENV
            docker build -t breadheadhub/$IMAGE_NAME:$IMAGE_TAG .
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
            docker push breadheadhub/$IMAGE_NAME:$IMAGE_TAG

  dev:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: ssh $SSH_USER@$SSH_HOST "cd /home/cloud-user/www/oncohelp &&
            sudo docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" &&
            sudo docker pull breadheadhub/oncohelp-web &&
            sudo docker logout &&
            sudo docker-compose down &&
            sudo docker-compose up -d &&
            sudo docker image prune -f"

  prod:
    machine:
      enabled: true
    steps:
      - run:
          name: Setup Env
          command: |
            echo 'export IMAGE_TAG=stable' >> $BASH_ENV
      - run:
          name: Deploy Over SSH
          command: |
            source $BASH_ENV
            ssh $SSH_PROD_USER@$SSH_PROD_HOST "cd /root/web &&
            sudo docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" &&
            sudo docker pull breadheadhub/oncohelp-web:$IMAGE_TAG &&
            sudo docker logout &&
            sudo docker-compose down &&
            sudo docker-compose up -d &&
            sudo docker image prune -f"

workflows:
  version: 2
  check-pr:
    jobs:
      - lint:
          filters:
            branches:
              ignore: 
                - master
      - test:
          filters:
            branches:
              ignore: 
                - master
      - types:
          filters:
            branches:
              ignore: 
                - master
      - cicular:
          filters:
            branches:
              ignore: 
                - master
  deploy-dev:
    jobs:
      - push:
          filters:
            branches:
              only: 
                - master
      - dev:
          filters:
            branches:
              only: 
                - master
          requires:
            - push
  deploy-prod:
    jobs:
      - push_stable:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - prod:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - push_stable
