version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8.11.1

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - js-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: js-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Lint Code
          command: yarn lint:code
      - run:
          name: Link Styles
          command: yarn lint:style

workflows:
  version: 2
  check-pr:
    jobs:
      - lint:
          filters:
            branches:
              ignore: 
                - master

