export const fail = {
  gender: 'Мужской',
  age: '76678',
  symptoms: {
    temperature: true,
    'sore-throat': true,
    thorax: true,
    cough: true,
    chills: true,
    dyspnea: true,
    'loose-stools': true,
    sneezing: true,
    'runny-nose': true,
    weakness: true,
    'body-aches': true,
    headache: true,
    nausea: true,
    'abdominal-pain': true,
  },
  caughtType: 'Сухой без мокроты',
  thoraxType: {
    coughing: true,
    inhale: true,
    'physical-activity': true,
    rest: true,
  },
  temperatureType: '38-39 градусов',
  dyspneaType: { rest: true, 'physical-activity': true },
  symptomsSince: 'Несколько недель назад',
  target: 'Для себя',
  region: 'Ивановская область',
  deseases: {
    diabetes: true,
    cardiovascular: true,
    oncological: true,
    COPD: true,
  },
}
