export const newClaimUTM = 'utm_source=new-claim'
export const finishClaimUTM = 'utm_source=finish-claim'
export const expertAnswersUTM = 'utm_medium=expert-answers-cabinet'
export const finishYesUTM = 'utm_medium=finish-yes-cabinet'
export const finishNoUTM = 'utm_medium=finish-no-cabinet'
