export enum RouteType {
  landing = '/landing',
  landingRequest = '/landing/request',
  landingVolunteer = '/landing/help-volunteers',
  landingHelp = '/landing/help',
  landingHospitalAid = '/landing/hospital-aid',
  landingRequestChat = '/landing/request-chat',
  landingPartners = '/landing/partners',
  landingContacts = '/landing/contacts',
  expertBoard = '/supervisory',
  expertBoardExpert = '/supervisory',
  landingExperts = '/landing/experts',
  landingExpert = '/landing/expert',
  landingForHospitals = '/landing/for-hospitals',
  helpVolunteers = '/landing/help-volunteers',
  helpPartners = '/landing/help-partners',
  ask = '/ask',
  askAbout = '/ask#about',
  landingNews = '/landing/news',
}
